set nocompatible               " be iMproved
filetype off                   " required!

set rtp+=~/.vim/bundle/vundle/
call vundle#rc()

" let Vundle manage Vundle
" required! 
Bundle 'gmarik/vundle'

Bundle 'kien/ctrlp.vim'
Bundle 'mileszs/ack.vim'
Bundle 'ervandew/supertab'
Bundle 'tpope/vim-unimpaired'
Bundle 'kchmck/vim-coffee-script'
Bundle 'tpope/vim-commentary'
Bundle 'tpope/vim-surround'
Bundle 'nono/vim-handlebars'

" ================
" Ruby stuff
" ================
syntax on                 " Enable syntax highlighting
filetype plugin indent on " Enable filetype-specific indenting and plugins

augroup myfiletypes
  " Clear old autocmds in group
  autocmd!
  " autoindent with two spaces, always expand tabs
  autocmd FileType ruby,eruby,yaml set ai sw=2 sts=2 et
augroup END
" ================

let mapleader = ","
set nocompatible
set list
set backspace=indent,eol,start " allow backspacing over everything in insert mode
set history=500" keep 500 lines of command line history
set ruler" show the cursor position all the time
set showcmd" display incomplete commands
set autoindent
set showmatch
set nowrap
set expandtab
set smarttab
set tabstop=2
set shiftwidth=2
set autoread

" List chars
set listchars=""
set listchars=tab:\ \
set listchars+=trail:.
set listchars+=extends:>
set listchars+=precedes:<

nmap <leader>fef ggVG=`` 
nmap <leader>, :e.<CR>
nmap <leader>b :b#<CR>
nmap <F5> :so $MYVIMRC<CR>

vmap <D-]> >gv
vmap <D-[> <gv

nmap <A-]> >>
nmap <A-[> <<

omap <D-]> >>
omap <D-[> <<

imap <D-]> <Esc>>>i
imap <D-[> <Esc><<i
