set nocompatible               " Round here we say Vim, not Vi
filetype off                   " required!

set rtp+=~/.vim/bundle/vundle/
call vundle#rc()

" Vundle
Bundle 'gmarik/vundle'

Bundle 'kien/ctrlp.vim'
Bundle 'mileszs/ack.vim'
Bundle 'ervandew/supertab'
Bundle 'tpope/vim-unimpaired'
Bundle 'kchmck/vim-coffee-script'
Bundle 'tpope/vim-commentary'
Bundle 'tpope/vim-surround'
Bundle 'tpope/vim-rails'
Bundle 'nono/vim-handlebars'
Bundle 'elixir-lang/vim-elixir'

" ================
" Ruby stuff
" ================
syntax on                 " Enable syntax highlighting
filetype plugin indent on " Enable filetype-specific indenting and plugins

augroup myfiletypes
  " Clear old autocmds in group
  autocmd!
  " autoindent with two spaces, always expand tabs
  autocmd FileType ruby,eruby,yaml set ai sw=2 sts=2 et
augroup END
" ================

let mapleader = ","
" Basic config that I cannot live without
set list
set backspace=indent,eol,start  " allow backspacing over everything in insert mode
set history=500                 " keep 500 lines of command line history
set ruler                       " show the cursor position all the time
set showcmd                     " display incomplete commands
set autoindent
set showmatch
set number
set nowrap
set expandtab
set smarttab
set tabstop=2
set shiftwidth=2
set autoread
set hlsearch

" List chars show whitespace and do not wrap lines
set listchars=""
set listchars=tab:\ \
set listchars+=trail:.
set listchars+=extends:>
set listchars+=precedes:<

" format the current file
nmap <leader>fef ggVG=`` 
" equally resize splits
nmap <leader>= <C-w>=

" Qucikly show navigation at the root
nmap <leader>, :e.<CR>
" Back to the last buffer
nmap <leader>b :b#<CR>
nnoremap <silent> [b :bprevious<CR>
nnoremap <silent> ]b :bprevious<CR>
nnoremap <silent> <C-l> :<C-u>nohlsearch<CR><C-l>
nmap <leader>l :ls<CR>
" Reload the vimrc config
nmap <F5> :so $MYVIMRC<CR>
" Resize equally
nmap <leader>= <C-w>=
nmap <leader>s :Ack 

" Indentation helpers
vmap <D-]> >gv
vmap <D-[> <gv
nmap <A-]> >>
nmap <A-[> <<
omap <D-]> >>
omap <D-[> <<
imap <D-]> <Esc>>>i
imap <D-[> <Esc><<i

" Taking notes are we? Code notes are excluded globally in git
nmap <leader>tn :e notes.scratch.md<CR>
" Remember to sharpen when possible and applicable
nmap <leader>ts :e ~/Dropbox/tool_sharpener.md<CR>

" Rspec.vim mappings
map <Leader>t :! bundle exec rspec<CR>
