set nocompatible               " Round here we say Vim, not Vi
filetype off                   " required!

set shell=/bin/bash
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
" Vundle
Plugin 'gmarik/Vundle.vim'
Plugin 'kien/ctrlp.vim'
Plugin 'mileszs/ack.vim'
Plugin 'ervandew/supertab'
Plugin 'tpope/vim-unimpaired'
Plugin 'kchmck/vim-coffee-script'
Plugin 'tpope/vim-commentary'
Plugin 'tpope/vim-rails'
Plugin 'nono/vim-handlebars'
Plugin 'fatih/vim-go'
call vundle#end()
filetype plugin indent on

" ================
" Ruby stuff
" ================
syntax on                 " Enable syntax highlighting
augroup myfiletypes
  " Clear old autocmds in group
  autocmd!
  " autoindent with two spaces, always expand tabs
  autocmd FileType ruby,eruby,yaml set ai sw=2 sts=2 et
augroup END
" ================

let mapleader = ","
" Basic config that I cannot live without
set list
set backspace=indent,eol,start  " allow backspacing over everything in insert mode
set history=500                 " keep 500 lines of command line history
set ruler                       " show the cursor position all the time
set showcmd                     " display incomplete commands
set autoindent
set showmatch
set number
set nowrap
set expandtab
set smarttab
set tabstop=2
set shiftwidth=2
set autoread

" List chars show whitespace and do not wrap lines
set listchars=""
set listchars=tab:\ \
set listchars+=trail:.
set listchars+=extends:>
set listchars+=precedes:<

" format the current file
nmap <leader>fef ggVG=``
" Quickly show navigation at the root
nmap <leader>, :Explore<CR>
nmap <leader>. :e.<CR>
" Back to the last buffer
nmap <leader>b :b#<CR>
nmap <leader>l :ls<CR>
" Reload the vimrc config
nmap <F5> :so $MYVIMRC<CR>
" Resize equally
nmap <leader>= <C-w>=
" Fast Search
nmap <leader>s :Ack
" Reload caches
nmap <leader>r :CtrlPClearCache<CR>
" Pretty json please!
nmap <leader>j :%!python -m json.tool<CR>
" Yep ignore these in the fuzzy finder ctrlp
let g:ctrlp_custom_ignore = 'node_modules\|DS_Store\|git'
" Taking notes are we? Code notes are excluded globally in git
nmap <leader>tn :e notes.scratch.md<CR>
nmap <leader>v :Vex<CR>
nmap <leader>s :Sex<CR>

" Strip trailing whitespace
autocmd BufWritePre * :%s/\s\+$//e

let g:go_fmt_command = "goimports"

" Use ag instead of grep
set grepprg=ag\ --nogroup\ --nocolor
let g:ackprg = 'ag --nogroup --column'
" Use ag in CtrlP for listing files. Lightning fast and respects .gitignore
let g:ctrlp_user_command = 'ag %s -l --nocolor -g ""'
