# Path to your oh-my-zsh configuration.
ZSH=$HOME/.oh-my-zsh

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
ZSH_THEME="robbyrussell"

# All about history, lots of it
HISTSIZE=20000
HISTFILE=~/.zsh_history
SAVEHIST=20000

plugins=(git bundler)

# Todo.txt, the only todo list I find useful
source /usr/local/Cellar/todo-txt/2.9/etc/bash_completion.d/todo_completion complete -F _todo t
export EDITOR='vim'
export ACKRC='~/.ackrc'

source $HOME/.dotfiles/aliases
source $HOME/.dotfiles/functions
source $HOME/.dotfiles/paths
source $ZSH/oh-my-zsh.sh
